-- Superseded: its effects (EmailVerificationCode table, indexes, FK) are
-- included in 0_init. The original TIMESTAMP(3) conversion of
-- User.emailVerified contradicted the Boolean schema and is intentionally
-- dropped.
